### ISSUE TITLE
ServiceBusJms and App Registration (tenant)

### ISSUE THREAD

**Issue by fciappa** [Azure/azure-servicebus-jms#20]
Hi,
we have implemented ServiceBusJmsFactory to send/receive messages with Shared Access key authentication.
Now we need to use Azure App Registration that requires Client ID, Client Secret and Tenant ID without losing Jms implementation.
Is this possible?

Thanks,
Francesco Ciappa

**Comment by ivan909020** [comment]
Can be implemented here #28

**Comment by EldertGrootenboer** [comment]
This is now available through our [latest JMS package](https://techcommunity.microsoft.com/t5/messaging-on-azure-blog/announcing-azure-active-directory-backed-authentication-for-jms/ba-p/3771409), see this announcement for more details.
