### ISSUE TITLE
What about archiving the project?

### ISSUE THREAD

**Issue by OleksandrShkurat** [Azure/azure-servicebus-jms#29]
Looks like the project is dead and should be archived in order to avoid misunderstanding.
People should know that it's not recommended to use it anywhere as it uses outdated azure libraries under the hood.
Take a look at the [picture](http://www.plantuml.com/plantuml/svg/hPdFSjis4CRlV0fDSkYbW2LJ-PCSccGIPoOpdRRJQKzY3Z29q7359GE2dRfFNq88ImU6FW6qnkEBjVlx5el5UY6yxOtGPcZssGytndJzwukBRY_8_eMNRNCn_dOjIJAiKgBMeicoR2V-7RHalTH_gr9U3_tdbUXNJqPJtgXIjttxnV23JK6-QK4vVy7Nx5eQmJS5VRZwxVUhz-_-kFhmPFMqK_HNjllQgOfrkZKjiLic_p6IUjKIKZdcKj26N_9jKCP5LkwLNPmOp8qaeqfXHZ-W1Bois0k-GMfp7jXj0zCMC2zepTVyLK5__lBhnu-Vtdzwz_E8rxBATaqlzjjRm7C6Di9DplD0X1E3TLBtgZUIIZad4f61sq6Fhq-dNmzaL2E1JCWS9xmwaH9dKD0RFlw040LHQuGvKO4FR0zhNuSNFw7BLizhdaZpHnQHF___i8pUUrNVc5hBk_i4PWyk8sdCNHZcMxaoECqLpTSE4Utd1LtoLo6Kf8cbAdj6p9rtb7rgsF9R2K7m2Pehapo4SEje18bQDgDrcEHR7MBQ75dqH6vatujQKUttIHyVDYt8LlOnZMpNTzewbFjsg9Z373gvr4oHaRK-LE5nRUu01IM32jhov-70K5Zf-Z52zqDqpj4hHguBr_YuT9zJdjqsCI5WmE8mZ9QYIKu6PYG7um3NYghuZS68SuSIwlyW7in93KeCfYrR-gBg0GU1_595jUpRGPVIzLBS4w3dijw0ymsSOkJcBfxMY83Z0jaKhVJzSw5XaP17ib3ioOZSesmtNGuSjDKr5vqeRoItLuU2fe_jZ9td_AKNeJMo7V7R07e4ubbPrhFSdrrE30Xiz_HWz-Drkwy-ivzMtusAhrSRdZ_ZwrI6DxHPq2L_oJV9dF3GQSFQZC1fRJv5osfcJAcsRYxP4LxWKcZ5B_as0eAlV9PZPwxuuGhc2a2irlrQFQyW78byvUXfXgKlAPeBYj1onqt9HsByv7F6xKWNydk5fRi-aCKFJJ3dOBJ1kukziHwONt3suZNHU7963J2DnAOF98CjFOdfMebd1uIKtbFGrgUhW448LpRsYHNowGlXZ-vY8MZoqJWv_gPd1USyZ0Ipeu-5nXYDYn5WEO_Ri0WC-9RB3KQsy-DzV7mI8_YSftV1TFJofWVOu7zgB24yHSSxfnSAXk5oyGVsg7l1d5Vi7pzH0mgOvWFN9RPxw921Yr_iBIWPCALz6lTpo8Y_HgL3l2-UtTwlxUQ7BPQN0ARWIrqE-tIWUR2K5Xr-5WlVs_m-ae-WRIm0pUH-OSJL7l2BlIr78AQ7lMapyWWV_90tznZKY1WwCVZfrCzz-A5llcqdmgef7szIFVq7EWT1pyriXziSJZJUpEsu1MybLKEp_my0). This project is red on it. Consider using libraries marked as green

**Comment by EldertGrootenboer** [comment]
We already removed the Java dependency that was causing the outdated dependencies. This project is still under active development.
