### ISSUE TITLE
Deprecated LATEST version is specified for a dependency of azure-servicebus-jms

### ISSUE THREAD

**Issue by Netyyyy** [Azure/azure-servicebus-jms#41]
Relates to https://github.com/Azure/azure-sdk-for-java/issues/38616,
any plan to remove the LATEST version?

**Comment by EldertGrootenboer** [comment]
We are currently doing active development on moving to the latest packages.

**Comment by ksalazar-91** [comment]
Issue has been addressed with pr https://github.com/Azure/azure-servicebus-jms/pull/44. New release will be done soon.

**Comment by ksalazar-91** [comment]
We have made release Serviceus JMS library, version 1.0.2 which fix issue
