### ISSUE TITLE
Cannot receive message from a sub dead letter queue

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-servicebus-jms#54]
Using below listener can process messages of the queue successfully:

 ```java
 @JmsListener(id ="jms", destination = "jms", containerFactory = "jmsListenerContainerFactory")
 public void receiveMessage(User user) {
     LOGGER.info("Received message from queue: {}", user.getName());
 }
 ```

I can think of below two ways to consume messages from the dead letter queue, but neither of them works:
1. Use @JmsListener

   ```java
    @JmsListener(id ="jmsDeadLetter", destination = "jms/$deadletterqueue", containerFactory = "jmsListenerContainerFactory")
    public void receiveDeadLetterMessage(User user) {
        LOGGER.info("Received dead letter message: {}", user.getName());
    }
   ```
3. Use JmsTemplate
   
    ```java
   jmsTemplate.receive(new JmsQueue("jms/$deadletterqueue"));
    ```

Could you help provide commended ways to consume the dead letter queue messages (DL of queue and topic)?

Spring: Spring Boot 3.3.3 + com.azure.spring:spring-cloud-azure-starter-servicebus-jms:5.18.0
Lib: com.azure:azure-servicebus-jms:2.0.0

**Comment by vinaysurya** [comment]
Is "jms" a queue or a subscription? Is the namespace a premium servicebus namespace or standard?

**Comment by vinaysurya** [comment]
This was happening because the messages were actually in deferred not deadlettered. This can be confirmed by peeking the queue from the ServiceBus portal and the state of the messages will show up as deferred. If the messages are actually deadlettered just using <queueName>/$deadletterqueue should work.
